{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Setup and Obtain the Data \n",
    "## Import Libraries and Dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: labelme in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (5.3.1)\n",
      "Requirement already satisfied: tensorflow in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (2.13.0)\n",
      "Collecting tensorflow-gpu\n",
      "  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: opencv-python in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (4.8.0.76)\n",
      "Requirement already satisfied: matplotlib in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (3.5.2)\n",
      "Requirement already satisfied: albumentations in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (1.3.1)\n",
      "Requirement already satisfied: pillow in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (9.2.0)\n",
      "Requirement already satisfied: natsort>=7.1.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (8.4.0)\n",
      "Requirement already satisfied: onnxruntime>=1.14.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (1.16.0)\n",
      "Requirement already satisfied: qtpy!=1.11.2 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (2.2.0)\n",
      "Requirement already satisfied: PyYAML in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (6.0)\n",
      "Requirement already satisfied: numpy in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (1.24.3)\n",
      "Requirement already satisfied: scikit-image in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (0.19.2)\n",
      "Requirement already satisfied: termcolor in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (2.3.0)\n",
      "Requirement already satisfied: gdown in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (4.7.1)\n",
      "Requirement already satisfied: imgviz>=0.11 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from labelme) (1.7.4)\n",
      "Requirement already satisfied: tensorflow-macos==2.13.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (2.13.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (2.0.0)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (4.24.3)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.58.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (3.7.0)\n",
      "Requirement already satisfied: setuptools in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (63.4.1)\n",
      "Requirement already satisfied: typing-extensions<4.6.0,>=3.6.6 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (4.3.0)\n",
      "Requirement already satisfied: flatbuffers>=23.1.21 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (23.5.26)\n",
      "Requirement already satisfied: packaging in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (21.3)\n",
      "Requirement already satisfied: keras<2.14,>=2.13.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (2.13.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (3.3.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.14.1)\n",
      "Requirement already satisfied: tensorboard<2.14,>=2.13 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (2.13.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (0.4.0)\n",
      "Requirement already satisfied: six>=1.12.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.16.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.6.3)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: tensorflow-estimator<2.14,>=2.13.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (2.13.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorflow-macos==2.13.0->tensorflow) (16.0.6)\n",
      "Collecting python_version>\"3.7\"\n",
      "  Downloading python_version-0.0.2-py2.py3-none-any.whl (3.4 kB)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from matplotlib) (1.4.2)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from matplotlib) (3.0.9)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from matplotlib) (2.8.2)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from matplotlib) (4.25.0)\n",
      "Requirement already satisfied: scipy>=1.1.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from albumentations) (1.9.1)\n",
      "Requirement already satisfied: qudida>=0.0.4 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from albumentations) (0.0.4)\n",
      "Requirement already satisfied: opencv-python-headless>=4.1.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from albumentations) (4.8.0.76)\n",
      "Requirement already satisfied: coloredlogs in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from onnxruntime>=1.14.1->labelme) (15.0.1)\n",
      "Requirement already satisfied: sympy in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from onnxruntime>=1.14.1->labelme) (1.10.1)\n",
      "Requirement already satisfied: scikit-learn>=0.19.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from qudida>=0.0.4->albumentations) (1.1.1)\n",
      "Requirement already satisfied: tifffile>=2019.7.26 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-image->labelme) (2021.7.2)\n",
      "Requirement already satisfied: PyWavelets>=1.1.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-image->labelme) (1.3.0)\n",
      "Requirement already satisfied: networkx>=2.2 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-image->labelme) (2.8.4)\n",
      "Requirement already satisfied: imageio>=2.4.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-image->labelme) (2.19.3)\n",
      "Requirement already satisfied: requests[socks] in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from gdown->labelme) (2.28.1)\n",
      "Requirement already satisfied: tqdm in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from gdown->labelme) (4.64.1)\n",
      "Requirement already satisfied: filelock in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from gdown->labelme) (3.6.0)\n",
      "Requirement already satisfied: beautifulsoup4 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from gdown->labelme) (4.11.1)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow-macos==2.13.0->tensorflow) (0.37.1)\n",
      "Requirement already satisfied: joblib>=1.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (1.1.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations) (2.2.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (0.7.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.0.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (3.3.4)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.23.0)\n",
      "Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (1.0.0)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4->gdown->labelme) (2.3.1)\n",
      "Requirement already satisfied: humanfriendly>=9.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from coloredlogs->onnxruntime>=1.14.1->labelme) (10.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests[socks]->gdown->labelme) (2022.9.24)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests[socks]->gdown->labelme) (3.3)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests[socks]->gdown->labelme) (1.26.11)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests[socks]->gdown->labelme) (2.0.4)\n",
      "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests[socks]->gdown->labelme) (1.7.1)\n",
      "Requirement already satisfied: mpmath>=0.19 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from sympy->onnxruntime>=1.14.1->labelme) (1.2.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (5.3.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (4.9)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (0.2.8)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (1.3.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/stevenwong/opt/anaconda3/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (3.2.2)\n",
      "Building wheels for collected packages: tensorflow-gpu\n",
      "  Building wheel for tensorflow-gpu (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/44/jj50yyvd6fb9m109s2slr96w0000gn/T/pip-install-v81whnsx/tensorflow-gpu_0b055becd2534ce4b4fc427371bb49a5/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for tensorflow-gpu\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for tensorflow-gpu\n",
      "Failed to build tensorflow-gpu\n",
      "Installing collected packages: python_version, tensorflow-gpu\n",
      "  Running setup.py install for tensorflow-gpu ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mRunning setup.py install for tensorflow-gpu\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/44/jj50yyvd6fb9m109s2slr96w0000gn/T/pip-install-v81whnsx/tensorflow-gpu_0b055becd2534ce4b4fc427371bb49a5/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mlegacy-install-failure\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while trying to install package.\n",
      "\u001b[31m╰─>\u001b[0m tensorflow-gpu\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for output from the failure.\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install labelme tensorflow tensorflow-gpu opencv-python matplotlib albumentations pillow"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Collect Images Using OpenCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os  # for accessing the file system\n",
    "import time  # for measuring the inference time per image\n",
    "import uuid  # for generating unique IDs for our images\n",
    "import cv2  # for computer vision tasks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "IMAGES_PATH = os.path.join('Tensorflow', 'images')\n",
    "number_of_images = 50"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image 0 saved\n",
      "Image 1 saved\n",
      "Image 2 saved\n",
      "Image 3 saved\n",
      "Image 4 saved\n",
      "Image 5 saved\n",
      "Image 6 saved\n",
      "Image 7 saved\n",
      "Image 8 saved\n",
      "Image 9 saved\n",
      "Image 10 saved\n",
      "Image 11 saved\n",
      "Image 12 saved\n",
      "Image 13 saved\n",
      "Image 14 saved\n",
      "Image 15 saved\n",
      "Image 16 saved\n",
      "Image 17 saved\n",
      "Image 18 saved\n",
      "Image 19 saved\n",
      "Image 20 saved\n",
      "Image 21 saved\n",
      "Image 22 saved\n",
      "Image 23 saved\n",
      "Image 24 saved\n",
      "Image 25 saved\n",
      "Image 26 saved\n",
      "Image 27 saved\n",
      "Image 28 saved\n",
      "Image 29 saved\n",
      "Image 30 saved\n",
      "Image 31 saved\n",
      "Image 32 saved\n",
      "Image 33 saved\n",
      "Image 34 saved\n",
      "Image 35 saved\n",
      "Image 36 saved\n",
      "Image 37 saved\n",
      "Image 38 saved\n",
      "Image 39 saved\n",
      "Image 40 saved\n",
      "Image 41 saved\n",
      "Image 42 saved\n",
      "Image 43 saved\n",
      "Image 44 saved\n",
      "Image 45 saved\n",
      "Image 46 saved\n",
      "Image 47 saved\n",
      "Image 48 saved\n",
      "Image 49 saved\n"
     ]
    }
   ],
   "source": [
    "# Collecting Images and name them with our unique IDs\n",
    "capture = cv2.VideoCapture(0)\n",
    "for i in range(number_of_images):\n",
    "    ret, frame = capture.read()\n",
    "    # Generate a unique ID for our image\n",
    "    img_id = uuid.uuid1()\n",
    "    img_name = os.path.join(IMAGES_PATH, f'image_{img_id}.jpg')\n",
    "    # Save the image\n",
    "    cv2.imwrite(img_name, frame)\n",
    "    cv2.imshow('frame', frame)\n",
    "    time.sleep(0.5)\n",
    "\n",
    "    # Break the loop when 'q' is pressed\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "    print(f'Image {i} saved')\n",
    "# Release the camera resource and desstroy the window opened by OpenCV\n",
    "capture.release()\n",
    "cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Annotating Images with Bounding Boxes in LabelMe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!labelme"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
